#!/usr/bin/env bash
# install.sh — stand up a sovereign Vulos relay in one command.
#
# The relay is the PUBLIC half of the Vulos reverse tunnel: the self-hosted
# replacement for a third-party frp server. A box elsewhere dials one outbound
# wss:// connection to this relay, and the relay serves it a public URL. You only
# need to run a relay if your box lacks public reachability (behind NAT/CGNAT) or
# you want a stable public hostname you control.
#
# This script:
#   1. Checks Docker + Docker Compose are present.
#   2. Generates a strong agent token and writes grants.json.
#   3. Writes a .env file consumed by docker-compose.yml.
#   4. (Unless --no-up) brings the relay up and health-checks it.
#
# Usage:
#   ./scripts/install.sh --domain relay.example.com
#   ./scripts/install.sh --domain relay.example.com --path-mode --name box1
#   ./scripts/install.sh --domain relay.example.com --no-up     # config only
#
# Run with no --domain and it will prompt for one. Re-running is safe: it will
# NOT overwrite an existing .env/grants.json unless you pass --force.
set -euo pipefail

# ── Resolve repo root (script lives in scripts/) ──────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ── Defaults / arg parsing ────────────────────────────────────────────────────
DOMAIN=""
NAME="box1"
PATH_MODE=0
FORCE=0
DO_UP=1
IMAGE=""

usage() { sed -n '2,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --domain)     DOMAIN="${2:-}"; shift 2 ;;
    --domain=*)   DOMAIN="${1#*=}"; shift ;;
    --name)       NAME="${2:-}"; shift 2 ;;
    --name=*)     NAME="${1#*=}"; shift ;;
    --image)      IMAGE="${2:-}"; shift 2 ;;
    --image=*)    IMAGE="${1#*=}"; shift ;;
    --path-mode)  PATH_MODE=1; shift ;;
    --no-up)      DO_UP=0; shift ;;
    --force)      FORCE=1; shift ;;
    -h|--help)    usage 0 ;;
    *) echo "install.sh: unknown option: $1" >&2; usage 1 ;;
  esac
done

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ── Preflight: docker + compose ───────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "docker not found — install Docker first (https://docs.docker.com/get-docker/)"
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "docker compose not found — install the Compose plugin"
fi

# ── Domain (prompt if unset) ──────────────────────────────────────────────────
if [ -z "$DOMAIN" ]; then
  printf 'Relay base domain (e.g. relay.example.com): '
  read -r DOMAIN || true
fi
[ -n "$DOMAIN" ] || die "a relay domain is required (--domain relay.example.com)"

# ── Strong token generator (openssl, else /dev/urandom) ───────────────────────
gen_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

GRANTS_FILE="$REPO_ROOT/grants.json"
ENV_FILE="$REPO_ROOT/.env"

# ── Grants file ───────────────────────────────────────────────────────────────
if [ -f "$GRANTS_FILE" ] && [ "$FORCE" -ne 1 ]; then
  warn "grants.json exists — keeping it (pass --force to regenerate)."
  TOKEN="$(grep -o '"token"[^,]*' "$GRANTS_FILE" | head -1 | sed 's/.*: *"//; s/".*//')"
  [ -n "$TOKEN" ] || warn "could not parse an existing token; agent examples below may be wrong."
else
  TOKEN="$(gen_token)"
  cat > "$GRANTS_FILE" <<EOF
[
  { "token": "$TOKEN", "names": ["$NAME"] }
]
EOF
  chmod 600 "$GRANTS_FILE"
  log "wrote grants.json (name=$NAME) — keep it secret; tokens are bearer credentials."
fi

# ── .env for docker-compose ───────────────────────────────────────────────────
if [ -f "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  warn ".env exists — keeping it (pass --force to regenerate)."
else
  # VULOS_RELAY_TOKENS carries the grants inline so no file mount is needed.
  TOKENS_INLINE="[{\"token\":\"$TOKEN\",\"names\":[\"$NAME\"]}]"
  {
    echo "# Generated by scripts/install.sh — consumed by docker-compose.yml."
    echo "VULOS_RELAY_DOMAIN=$DOMAIN"
    echo "VULOS_RELAY_TOKENS=$TOKENS_INLINE"
    echo "VULOS_RELAY_PATH_MODE=$([ "$PATH_MODE" -eq 1 ] && echo 1 || echo '')"
    echo "# ON when a trusted TLS-terminating proxy/CDN fronts the relay; OFF if directly internet-facing."
    echo "VULOS_RELAY_TRUST_PROXY_HEADERS=1"
    echo "RELAY_PUBLIC_PORT=8443"
    [ -n "$IMAGE" ] && echo "RELAY_IMAGE=$IMAGE"
    echo "# Optional Vulos Cloud account-linking/metering (empty ⇒ unbilled self-host):"
    echo "# VULOS_CP_URL="
    echo "# CP_SHARED_SECRET="
    echo "# VULOS_RELAY_POP_ID="
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  log "wrote .env (domain=$DOMAIN, path_mode=$PATH_MODE)"
fi

# ── DNS / TLS reminder ────────────────────────────────────────────────────────
cat <<EOF

Next, DNS + TLS (this relay speaks PLAIN HTTP — terminate TLS at your edge):
  - Subdomain mode (default): point  $DOMAIN  AND  *.$DOMAIN  at this host,
    with a *.$DOMAIN TLS cert at your reverse proxy / CDN.
$([ "$PATH_MODE" -eq 1 ] && echo "  - Path mode (enabled): point  $DOMAIN  at this host; tunnels served at https://$DOMAIN/t/<name>/." || echo "  - No wildcard DNS? re-run with --path-mode and use https://$DOMAIN/t/<name>/.")
  - Forward your proxy's :443 to this host's :8443 (RELAY_PUBLIC_PORT in .env).
EOF

# ── Bring it up ───────────────────────────────────────────────────────────────
if [ "$DO_UP" -ne 1 ]; then
  log "config written. Start it with:  $COMPOSE up -d"
  exit 0
fi

log "starting relay ($COMPOSE up -d) ..."
$COMPOSE up -d --build

# Health-check via the container's own healthcheck endpoint.
log "waiting for relay health ..."
ok=0
for _ in $(seq 1 20); do
  if docker exec vulos-relayd wget -qO- http://127.0.0.1:8443/healthz >/dev/null 2>&1; then
    ok=1; break
  fi
  sleep 1
done
if [ "$ok" -eq 1 ]; then
  log "relay is up and healthy."
else
  warn "relay did not report healthy yet — check:  $COMPOSE logs relay"
fi

cat <<EOF

Relay is running. On the box you want to expose, run the agent:

  vulos-relay-agent \\
    -server wss://$DOMAIN \\
    -token  $TOKEN \\
    -name   $NAME \\
    -local  127.0.0.1:8080

Then reach it at  https://$NAME.$DOMAIN$([ "$PATH_MODE" -eq 1 ] && echo "  (or https://$DOMAIN/t/$NAME/)")

Useful:
  $COMPOSE logs -f relay      # follow logs
  $COMPOSE down               # stop
  ./scripts/install.sh --force --domain $DOMAIN   # rotate token / rewrite config

Full walkthrough: docs/GETTING-STARTED.md   Flag/env reference: docs/TUNNEL.md
EOF
